# Add 'root' label to any root file changes
# Quotation marks are required for the leading asterisk
root:
  - changed-files:
      - any-glob-to-any-file: '*'

# Add 'documentation' label to any changes within 'docs' folder or any subfolders
documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**
      - any-glob-to-any-file: '**/*.md'

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
  - head-branch: ['^feature', 'feature', 'feat']

# Add 'release' label to any PR that is opened against the `main` branch
release:
  - base-branch: 'main'

jasonruesch:
  - changed-files:
      - any-glob-to-any-file: '**/jasonruesch/**'

tailwind:
  - changed-files:
      - any-glob-to-any-file: '**/tailwind/**'
      - any-glob-to-any-file: '**/tailwind.config.{js|ts}'
