# Run with:
# docker compose -f docker-compose.jasonruesch.yml up

services:
  jasonruesch:
    image: jasonruesch:dev
    container_name: jasonruesch-jasonruesch-dev
    build:
      context: .
      dockerfile: ./apps/jasonruesch/Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # To fix an issue with HMR on Windows machines
