/*
! tailwindcss v3.4.1 | MIT License | https://tailwindcss.com
*/ /*
1. Prevent padding and border from affecting element width. (https://github.com/mozdevs/cssremedy/issues/4)
2. Allow adding a border to an element by just adding a border-width. (https://github.com/tailwindcss/tailwindcss/pull/116)
*/
import { PluginUtils } from 'tailwindcss/types/config';

export default (theme: PluginUtils['theme']) => ({
  // Design foundations typically set on the html element,
  // but provided here when preflight is disabled,
  // or to override existing styles in a hybrid solution
  ':where(.reset, .reset *)': {
    'font-family': theme('fontFamily.sans'),
    'font-size': theme('fontSize.base'),
    'line-height': theme('lineHeight.6'),
    color: theme('colors.neutral-800'),
  },

  ':where(.reset, .reset *), :where(.reset, .reset *):before, :where(.reset, .reset *):after':
    {
      'box-sizing': 'border-box',
      'border-width': '0',
      'border-style': 'solid',
      'border-color': '#e5e7eb',
    },
  ':where(.reset, .reset *):before, :where(.reset, .reset *):after': {
    '--tw-content': '',
  },
  'html:where(.reset, .reset *)': {
    'line-height': '1.5',
    '-webkit-text-size-adjust': '100%',
    '-moz-tab-size': '4',
    '-o-tab-size': '4',
    'tab-size': '4',
    'font-family':
      "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', Segoe UI Symbol, 'Noto Color Emoji'",
    'font-feature-settings': 'normal',
  },
  'body:where(.reset, .reset *)': {
    margin: '0',
    'line-height': 'inherit',
  },
  'hr:where(.reset, .reset *)': {
    height: '0',
    color: 'inherit',
    'border-top-width': '1px',
  },
  'abbr:where(.reset, .reset *):where([title])': {
    '-webkit-text-decoration': 'underline dotted',
    'text-decoration': 'underline dotted',
  },
  'h1:where(.reset, .reset *)': {
    'font-size': 'inherit',
    'font-weight': 'inherit',
  },
  'h2:where(.reset, .reset *)': {
    'font-size': 'inherit',
    'font-weight': 'inherit',
  },
  'h3:where(.reset, .reset *)': {
    'font-size': 'inherit',
    'font-weight': 'inherit',
  },
  'h4:where(.reset, .reset *)': {
    'font-size': 'inherit',
    'font-weight': 'inherit',
  },
  'h5:where(.reset, .reset *)': {
    'font-size': 'inherit',
    'font-weight': 'inherit',
  },
  'h6:where(.reset, .reset *)': {
    'font-size': 'inherit',
    'font-weight': 'inherit',
  },
  'a:where(.reset, .reset *)': {
    color: 'inherit',
    'text-decoration': 'inherit',
  },
  'b:where(.reset, .reset *)': {
    'font-weight': 'bolder',
  },
  'strong:where(.reset, .reset *)': {
    'font-weight': 'bolder',
  },
  'code:where(.reset, .reset *)': {
    'font-family':
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
    'font-size': '1em',
  },
  'kbd:where(.reset, .reset *)': {
    'font-family':
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
    'font-size': '1em',
  },
  'samp:where(.reset, .reset *)': {
    'font-family':
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
    'font-size': '1em',
  },
  'pre:where(.reset, .reset *)': {
    'font-family':
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
    'font-size': '1em',
  },
  'small:where(.reset, .reset *)': {
    'font-size': '80%',
  },
  'sub:where(.reset, .reset *)': {
    'font-size': '75%',
    'line-height': '0',
    position: 'relative',
    'vertical-align': 'baseline',
    bottom: '-0.25em',
  },
  'sup:where(.reset, .reset *)': {
    'font-size': '75%',
    'line-height': '0',
    position: 'relative',
    'vertical-align': 'baseline',
    top: '-0.5em',
  },
  'table:where(.reset, .reset *)': {
    'text-indent': '0',
    'border-color': 'inherit',
    'border-collapse': 'collapse',
  },
  'button:where(.reset, .reset *)': {
    'font-family': 'inherit',
    'font-size': '100%',
    'font-weight': 'inherit',
    'line-height': 'inherit',
    color: 'inherit',
    margin: '0',
    padding: '0',
    'text-transform': 'none',
    cursor: 'pointer',
  },
  'input:where(.reset, .reset *)': {
    'font-family': 'inherit',
    'font-size': '100%',
    'font-weight': 'inherit',
    'line-height': 'inherit',
    color: 'inherit',
    margin: '0',
    padding: '0',
    'text-transform': 'none',
  },
  'optgroup:where(.reset, .reset *)': {
    'font-family': 'inherit',
    'font-size': '100%',
    'font-weight': 'inherit',
    'line-height': 'inherit',
    color: 'inherit',
    margin: '0',
    padding: '0',
    'text-transform': 'none',
  },
  'select:where(.reset, .reset *)': {
    'font-family': 'inherit',
    'font-size': '100%',
    'font-weight': 'inherit',
    'line-height': 'inherit',
    color: 'inherit',
    margin: '0',
    padding: '0',
    'text-transform': 'none',
  },
  'textarea:where(.reset, .reset *)': {
    'font-family': 'inherit',
    'font-size': '100%',
    'font-weight': 'inherit',
    'line-height': 'inherit',
    color: 'inherit',
    margin: '0',
    padding: '0',
    resize: 'vertical',
  },
  "input:where(.reset, .reset *)[type='button']": {
    '-webkit-appearance': 'button',
    'background-color': 'transparent',
    'background-image': 'none',
  },
  "input:where(.reset, .reset *)[type='reset']": {
    '-webkit-appearance': 'button',
    'background-color': 'transparent',
    'background-image': 'none',
  },
  "input:where(.reset, .reset *)[type='submit']": {
    '-webkit-appearance': 'button',
    'background-color': 'transparent',
    'background-image': 'none',
  },
  ':where(.reset, .reset *):-moz-focusring': {
    outline: 'auto',
  },
  ':where(.reset, .reset *):-moz-ui-invalid': {
    'box-shadow': 'none',
  },
  'progress:where(.reset, .reset *)': {
    'vertical-align': 'baseline',
  },
  ':where(.reset, .reset *)::-webkit-inner-spin-button': {
    height: 'auto',
  },
  ':where(.reset, .reset *)::-webkit-outer-spin-button': {
    height: 'auto',
  },
  ":where(.reset, .reset *)[type='search']": {
    '-webkit-appearance': 'textfield',
    'outline-offset': '-2px',
  },
  ':where(.reset, .reset *)::-webkit-search-decoration': {
    '-webkit-appearance': 'none',
  },
  ':where(.reset, .reset *)::-webkit-file-upload-button': {
    '-webkit-appearance': 'button',
    font: 'inherit',
  },
  'summary:where(.reset, .reset *)': {
    display: 'list-item',
  },
  'blockquote:where(.reset, .reset *)': {
    margin: '0',
  },
  'dl:where(.reset, .reset *)': {
    margin: '0',
  },
  'dd:where(.reset, .reset *)': {
    margin: '0',
  },
  'figure:where(.reset, .reset *)': {
    margin: '0',
  },
  'p:where(.reset, .reset *)': {
    margin: '0',
  },
  'fieldset:where(.reset, .reset *)': {
    margin: '0',
    padding: '0',
  },
  'legend:where(.reset, .reset *)': {
    padding: '0',
  },
  'ol:where(.reset, .reset *)': {
    'list-style': 'none',
    margin: '0',
    padding: '0',
  },
  'ul:where(.reset, .reset *)': {
    'list-style': 'none',
    margin: '0',
    padding: '0',
  },
  'menu:where(.reset, .reset *)': {
    'list-style': 'none',
    margin: '0',
    padding: '0',
  },
  'textarea:where(.reset, .reset *)::-moz-placeholder': {
    opacity: '1',
    color: '#9ca3af',
  },
  'textarea:where(.reset, .reset *)::placeholder': {
    opacity: '1',
    color: '#9ca3af',
  },
  "button:where(.reset, .reset *), :where(.reset, .reset *)[role='button']": {
    cursor: 'pointer',
  },
  ':where(.reset, .reset *):disabled': {
    cursor: 'default',
  },
  'img:where(.reset, .reset *)': {
    display: 'block',
    'vertical-align': 'middle',
    'max-width': '100%',
    height: 'auto',
  },
  'svg:where(.reset, .reset *)': {
    display: 'block',
    'vertical-align': 'middle',
    'max-width': '100%',
    height: 'auto',
  },
  'video:where(.reset, .reset *)': {
    display: 'block',
    'vertical-align': 'middle',
    'max-width': '100%',
    height: 'auto',
  },
  'canvas:where(.reset, .reset *)': {
    display: 'block',
    'vertical-align': 'middle',
    'max-width': '100%',
    height: 'auto',
  },
  'audio:where(.reset, .reset *)': {
    display: 'block',
    'vertical-align': 'middle',
    'max-width': '100%',
    height: 'auto',
  },
  'iframe:where(.reset, .reset *)': {
    display: 'block',
    'vertical-align': 'middle',
  },
  'embed:where(.reset, .reset *)': {
    display: 'block',
    'vertical-align': 'middle',
  },
  'object:where(.reset, .reset *)': {
    display: 'block',
    'vertical-align': 'middle',
  },
  ':where(.reset, .reset *)[hidden]': {
    display: 'none',
  },
  ':where(.reset, .reset *) :where(.reset, .reset *):before': {
    '--tw-border-spacing-x': '0',
    '--tw-border-spacing-y': '0',
    '--tw-translate-x': '0',
    '--tw-translate-y': '0',
    '--tw-rotate': '0',
    '--tw-skew-x': '0',
    '--tw-skew-y': '0',
    '--tw-scale-x': '1',
    '--tw-scale-y': '1',
    '--tw-pan-x': '',
    '--tw-pan-y': '',
    '--tw-pinch-zoom': '',
    '--tw-scroll-snap-strictness': 'proximity',
    '--tw-ordinal': '',
    '--tw-slashed-zero': '',
    '--tw-numeric-figure': '',
    '--tw-numeric-spacing': '',
    '--tw-numeric-fraction': '',
    '--tw-ring-inset': '',
    '--tw-ring-offset-width': '0px',
    '--tw-ring-offset-color': '#fff',
    '--tw-ring-color': 'rgb(59 130 246 / 0.5)',
    '--tw-ring-offset-shadow': '0 0 #0000',
    '--tw-ring-shadow': '0 0 #0000',
    '--tw-shadow': '0 0 #0000',
    '--tw-shadow-colored': '0 0 #0000',
    '--tw-blur': '',
    '--tw-brightness': '',
    '--tw-contrast': '',
    '--tw-grayscale': '',
    '--tw-hue-rotate': '',
    '--tw-invert': '',
    '--tw-saturate': '',
    '--tw-sepia': '',
    '--tw-drop-shadow': '',
    '--tw-backdrop-blur': '',
    '--tw-backdrop-brightness': '',
    '--tw-backdrop-contrast': '',
    '--tw-backdrop-grayscale': '',
    '--tw-backdrop-hue-rotate': '',
    '--tw-backdrop-invert': '',
    '--tw-backdrop-opacity': '',
    '--tw-backdrop-saturate': '',
    '--tw-backdrop-sepia': '',
  },
  ':where(.reset, .reset *)::after': {
    '--tw-border-spacing-x': '0',
    '--tw-border-spacing-y': '0',
    '--tw-translate-x': '0',
    '--tw-translate-y': '0',
    '--tw-rotate': '0',
    '--tw-skew-x': '0',
    '--tw-skew-y': '0',
    '--tw-scale-x': '1',
    '--tw-scale-y': '1',
    '--tw-pan-x': '',
    '--tw-pan-y': '',
    '--tw-pinch-zoom': '',
    '--tw-scroll-snap-strictness': 'proximity',
    '--tw-ordinal': '',
    '--tw-slashed-zero': '',
    '--tw-numeric-figure': '',
    '--tw-numeric-spacing': '',
    '--tw-numeric-fraction': '',
    '--tw-ring-inset': '',
    '--tw-ring-offset-width': '0px',
    '--tw-ring-offset-color': '#fff',
    '--tw-ring-color': 'rgb(59 130 246 / 0.5)',
    '--tw-ring-offset-shadow': '0 0 #0000',
    '--tw-ring-shadow': '0 0 #0000',
    '--tw-shadow': '0 0 #0000',
    '--tw-shadow-colored': '0 0 #0000',
    '--tw-blur': '',
    '--tw-brightness': '',
    '--tw-contrast': '',
    '--tw-grayscale': '',
    '--tw-hue-rotate': '',
    '--tw-invert': '',
    '--tw-saturate': '',
    '--tw-sepia': '',
    '--tw-drop-shadow': '',
    '--tw-backdrop-blur': '',
    '--tw-backdrop-brightness': '',
    '--tw-backdrop-contrast': '',
    '--tw-backdrop-grayscale': '',
    '--tw-backdrop-hue-rotate': '',
    '--tw-backdrop-invert': '',
    '--tw-backdrop-opacity': '',
    '--tw-backdrop-saturate': '',
    '--tw-backdrop-sepia': '',
  },
  ':where(.reset, .reset *)::backdrop': {
    '--tw-border-spacing-x': '0',
    '--tw-border-spacing-y': '0',
    '--tw-translate-x': '0',
    '--tw-translate-y': '0',
    '--tw-rotate': '0',
    '--tw-skew-x': '0',
    '--tw-skew-y': '0',
    '--tw-scale-x': '1',
    '--tw-scale-y': '1',
    '--tw-pan-x': '',
    '--tw-pan-y': '',
    '--tw-pinch-zoom': '',
    '--tw-scroll-snap-strictness': 'proximity',
    '--tw-ordinal': '',
    '--tw-slashed-zero': '',
    '--tw-numeric-figure': '',
    '--tw-numeric-spacing': '',
    '--tw-numeric-fraction': '',
    '--tw-ring-inset': '',
    '--tw-ring-offset-width': '0px',
    '--tw-ring-offset-color': '#fff',
    '--tw-ring-color': 'rgb(59 130 246 / 0.5)',
    '--tw-ring-offset-shadow': '0 0 #0000',
    '--tw-ring-shadow': '0 0 #0000',
    '--tw-shadow': '0 0 #0000',
    '--tw-shadow-colored': '0 0 #0000',
    '--tw-blur': '',
    '--tw-brightness': '',
    '--tw-contrast': '',
    '--tw-grayscale': '',
    '--tw-hue-rotate': '',
    '--tw-invert': '',
    '--tw-saturate': '',
    '--tw-sepia': '',
    '--tw-drop-shadow': '',
    '--tw-backdrop-blur': '',
    '--tw-backdrop-brightness': '',
    '--tw-backdrop-contrast': '',
    '--tw-backdrop-grayscale': '',
    '--tw-backdrop-hue-rotate': '',
    '--tw-backdrop-invert': '',
    '--tw-backdrop-opacity': '',
    '--tw-backdrop-saturate': '',
    '--tw-backdrop-sepia': '',
  },
});
