FROM nginx:stable-alpine

ENV NODE_ENV=production

WORKDIR /usr/share/nginx/html

# Remove default nginx static resources
RUN rm -rf ./*

COPY ./dist/apps/jasonruesch .
COPY ./apps/jasonruesch/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]
