export * from './about/about';
export * from './articles/articles';
export * from './contact/contact';
export * from './easter-egg/easter-egg';
export * from './home/home';
export * from './privacy/privacy';
export * from './projects/projects';
export * from './transparent/transparent';
export * from './uses/uses';
