name: Main Branch CI

on:
  push:
    branches:
      - ci-main
      # - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these deployments to complete.
concurrency:
  group: 'main'
  cancel-in-progress: false

jobs:
  # Affected job
  affected:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release):') }}
    name: Affected
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set SHAs for Nx
        uses: nrwl/nx-set-shas@v4

      # - name: Run format check
      #   run: npx nx-cloud record -- nx format:check

      # - name: Run affected lint and tests
      #   run: npx nx affected -t lint test e2e-ci

      - name: Affected projects
        id: projects
        run: |
          # PROJECTS=$(npx nx show projects --projects jasonruesch --affected --with-target build | tr '\n' ' ' | xargs)
          PROJECTS=$(npx nx show projects --projects jasonruesch --with-target build | tr '\n' ' ' | xargs)
          echo "projects=($PROJECTS)" >> $GITHUB_OUTPUT

      - name: Affected versions
        id: versions
        run: |
          projects=${{ steps.projects.outputs.projects }}
          items="["
          for project in "${projects[@]}"; do
            version=$(npm version prerelease --preid=staging --no-git-tag-version --prefix ./apps/$project/)
            items+="{\"project\":\"$project\",\"version\":\"$version\"},"
          done
          items=$(echo "$items" | sed 's/,$//g')
          items+="]"
          echo "matrix={\"include\":$items}" >> $GITHUB_OUTPUT

  # Build job
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: affected
    if: ${{ needs.affected.outputs.matrix != '' && needs.affected.outputs.matrix.include != '[]' }}
    strategy:
      matrix: ${{ fromJson(needs.affected.outputs.matrix) }}
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Configure Git Identity
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Update version
        run: npm version ${{ matrix.version }} --no-git-tag-version --prefix ./apps/${{ matrix.project }}/

      - name: Build
        run: npx nx build ${{ matrix.project }} --skip-nx-cache

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages-${{ matrix.project }}
          path: ./dist/apps/${{ matrix.project }}

      - name: Commit version bump
        run: |
          git add ./apps/${{ matrix.project }}/package.json
          git commit -m "chore(release): ${{ matrix.project }}@${{ matrix.version }}" -n
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Push changes
        run: |
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

  # Deployment job
  deploy:
    name: Deploy
    environment:
      name: Staging
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - affected
      - build
    if: ${{ needs.affected.outputs.matrix != '' && needs.affected.outputs.matrix.include != '[]' }}
    strategy:
      matrix: ${{ fromJson(needs.affected.outputs.matrix) }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ matrix.project }}
