# This workflow will test, build, and deploy a site to Vercel's Preview environment

name: Pull Request CI/CD

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: read
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# Cancel in-progress runs.
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Affected job
  affected:
    if: github.event.pull_request.draft == false
    name: Affected
    runs-on: ubuntu-latest
    outputs:
      apps-matrix: ${{ steps.apps.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Set SHAs for Nx
        uses: nrwl/nx-set-shas@v4

      - name: Run format check
        run: npx nx-cloud record -- nx format:check

      - name: Run affected lint and tests
        run: npx nx affected -t lint test e2e-ci

      - name: Affected deployable apps
        id: apps
        run: |
          projects=$(npx nx show projects --type app --affected --with-target version | tr '\n' ' ' | xargs)
          list=($projects)
          items="["
          for project in "${list[@]}"; do
            path=$(npx nx show project $project | jq -r .root)
            items+="{\"project\":\"$project\",\"path\":\"$path\"},"
          done
          items=$(echo "$items" | sed 's/,$//g')
          items+="]"
          [[ $items = "[]" ]] && matrix="" || matrix="{\"include\":$items}"
          echo "$projects"
          echo "projects=$projects" >> $GITHUB_OUTPUT
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

      - name: Build affected non-deployable apps and all affected libs
        run: |
          projects+=(${{ steps.apps.outputs.projects }})
          echo "$projects[@]"
          npx nx affected -t build --exclude "$projects[@]"

  # Build job
  build-app:
    name: Build App
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    needs: affected
    if: ${{ needs.affected.outputs.apps-matrix != '' }}
    strategy:
      matrix: ${{ fromJson(needs.affected.outputs.apps-matrix) }}
    outputs:
      project: ${{ matrix.project }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        run: vercel build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project }}
          path: .vercel/output

  # Deploy job
  deploy-preview-jasonruesch:
    name: Deploy Jason Ruesch to Preview
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    environment:
      name: Preview
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - affected
      - build-app
    if: ${{ needs.affected.outputs.apps-matrix != '' && needs.build-app.outputs.project == 'jasonruesch'}}
    strategy:
      matrix: ${{ fromJson(needs.affected.outputs.apps-matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.project }}
          path: .vercel/output

      - name: Deploy Project Artifacts to Vercel
        id: deployment
        run: |
          url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > /dev/stdout)
          echo "$url"
          echo "page_url=$url" >> $GITHUB_OUTPUT
