name: Preview

on:
  # Run this workflow on every PR event. Existing preview apps will be updated when the PR is updated.
  pull_request:
    types: [opened, reopened, synchronize, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  deploy-jasonruesch-preview:
    environment:
      # Deploying apps with this "preview" environment allows the URL for the app to be displayed in the PR UI.
      name: Preview
      # The script in the `deploy` sets the URL output for each review app.
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4

      - id: deploy
        uses: superfly/fly-pr-review-apps@1.3.0
        with:
          name: ${{ github.event.repository.name }}-pr-${{ github.event.number }}
          config: apps/jasonruesch/fly.preview.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
