name: Production

on:
  push:
    tags:
      - v*.*.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  deploy-jasonruesch:
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    concurrency: deploy-jasonruesch
    steps:
      - uses: actions/checkout@v4

      - id: deploy
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config apps/jasonruesch/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
